# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout backend
      uses: actions/checkout@v2
        
    - name: checkout frontend
      uses: actions/checkout@v2
      with:
        repository: Couch-Coders/7th-for_rest-fe
        path: ./frontend
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'        
        
    - name: gradlew 권한 부여
      run: chmod +x ./gradlew
        
    - name: Gradle 빌드
      run: ./gradlew build -x test
      shell: bash
      
#     - name: 단위 테스트 실행
#       run: SPRING_PROFILES_ACTIVE=[test] ./gradlew test
      
#     - name: 유닛 테스트 결과 기록
#       uses: EnricoMi/publish-unit-test-result-action@v1
#       if: ${{ always() }}
#       with:
#         files: build/test-results/**/*.xml
#

    - name: build frontend to resources
      run: |
        cd frontend
        npm install
        npm run build
        cd ..
        mkdir src/main/resources/static/
        cp -r frontend/build/* src/main/resources/static/
      env:   
        CI: ""
      

    - name: deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "for-rest" #Must be unique in Heroku
        heroku_email: "tj4643@hanmail.net"
        remote_branch: "main"
